source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Avid-ly/iOS-CocoaPods-Spec.git'

platform :ios, '10.0'

target 'CSSDKDemo' do

# CSSDK
pod 'CSSDK', '2.1.0.8'

## AASDK
#pod 'AASDK', '2.0.0.2'

# TASDK
pod 'TASDK', '4.1.0.6'

end
