source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Avid-ly/iOS-CocoaPods-Spec.git'

platform :ios, '10.0'

target 'CSSDKDemo' do

# CSSDK
pod 'CSSDK', '2.1.1.1'

## AASDK
#pod 'AASDK', '2.0.0.5'

# TASDK
pod 'TASDK', '4.1.1.0'

end
